name: "Has line changed"
description: "Check if a line has changed in a file in a pull request or commit"
author: "Sébastien de Melo <sebastien@singlespot.com>"
branding:
  icon: "code"
  color: "blue"
inputs:
  file:
    description: "File to check"
    required: true
  line_pattern:
    description: "Line pattern to check"
    required: true
outputs:
  changed:
    description: "Whether the line has changed"
    value: ${{ steps.has-line-changed.outputs.changed }}
  line:
    description: "The line, whether it has changed or not"
    value: ${{ steps.has-line-changed.outputs.line }}
runs:
  using: "composite"
  steps:
    - name: Ensure that event is pull_request or push
      shell: bash
      run: |
        if [ "${{ github.event_name }}" != "pull_request" ] && [ "${{ github.event_name }}" != "push" ]; then
          echo "Event must be pull_request or push"
          exit 1
        fi
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: tmp
        fetch-depth: 0
    - name: Ensure that file exists
      shell: bash
      run: |
        if [ ! -f tmp/${{ inputs.file }} ]; then
          echo "File not found: ${{ inputs.file }}"
          exit 1
        fi
    - name: Run version extractor
      id: has-line-changed
      shell: bash
      run: |
        set -e
        case "${{ github.event_name }}" in
          push)
            before="${{ github.event.before }}"
            after="${{ github.event.after }}"
            ;;
          pull_request)
            before="${{ github.event.base_ref }}^"
            after="${{ github.event.head_ref }}"
            ;;
        esac
        echo "Diff between ${before} and ${after}"
        cd tmp
        output=$(git diff --unified=0 ${before} ${after} ${{ inputs.file }} | grep -E "${{ inputs.line_pattern }}")
        echo "Output: $output"
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo $output | grep -E "\+${{ inputs.line_pattern }}" | cut -c2- >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          grep -E "${{ inputs.line_pattern }}" tmp/${{ inputs.file }} >> $GITHUB_OUTPUT
        fi
    - name: Cleanup
      shell: bash
      run: |
        rm -rf tmp
