name: "Extract Python package version"
description: "Extracts the Python package version from pyproject.toml, setup.py, or setup.cfg"
author: "Sébastien de Melo <sebastien@singlespot.com>"
branding:
  icon: "code"
  color: "blue"
inputs:
  version:
    description: "The version to check"
    required: true
outputs:
  stable:
    description: "Whether the version is stable"
    value: ${{ steps.version-checker.outputs.stable }}
  dev:
    description: "Whether the version is dev"
    value: ${{ steps.version-checker.outputs.dev }}
  post:
    description: "Whether the version is post"
    value: ${{ steps.version-checker.outputs.post }}
  pre:
    description: "Whether the version is pre"
    value: ${{ steps.version-checker.outputs.pre }}
runs:
  using: "composite"
  steps:
    - name: Run version checker
      id: version-checker
      shell: bash
      run: |
        python ${{ github.action_path }}/check_version.py ${{ inputs.version }}
