name: "Extract Python package version"
description: "Extracts the Python package version from pyproject.toml, setup.py, or setup.cfg"
author: "Sébastien de Melo <sebastien@singlespot.com>"
branding:
  icon: "code"
  color: "blue"
inputs:
  file_path:
    description: "File path to extract the version from (pyproject.toml, setup.py or setup.cfg)"
    default: "pyproject.toml"
    required: false
outputs:
  version:
    description: "The extracted version"
runs:
  using: "composite"
  steps:
    - name: Run version extractor
      shell: bash
      run: |
        # If file_path basename is setup.py or setup.cfg, use python setup.py --version
        file_name=$(basename ${{ inputs.file_path }})
        if [ "$file_name" == "setup.py" ] || [ "$file_name" == "setup.cfg" ]; then
          VERSION=$(python ${{ inputs.file_path }} --version)
        else
          VERSION=$(python ${{ github.action_path }}/extract_version.py --pyproject ${{ inputs.file_path }})
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
